@startuml vehicle-edge-telemetry
== Sensor to server ==
entity Sensor
queue kafka
entity Server
Sensor->kafka: IMU/GPS/LIDAR logs streamed through LTE/LoRA
kafka->Server: Logs streamed to serve

== server to datastore ==
database NoSQLDB
Server->NoSQLDB: Logs from queue directed/stored in timeseriesDB

== datastore to ML model ==
entity MLModel
NoSQLDB->MLModel: Logs become part of training dataset of ML model

== serve to UI/Dashboard ==
entity Dashboard
Server->MLModel: New logs are passed through ML model for inference
Server->Dashboard: RUL(Remaining Useful Life) calculated from ML model is directed to UI
@enduml